version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: contenedor-bd
    environment:
      MYSQL_ROOT_PASSWORD: Admin$2024
      MYSQL_DATABASE: project_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - redProyecto

  springboot-app:
    build:
      context: ./backendProject/alm14 
      dockerfile: Dockerfile
    container_name: contenedor-Backend
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/project_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin$2024
    networks:
      - redProyecto

